ALTER TABLE DRIVER ADD COLUMN DRIVER_STAR DECIMAL(3, 2) DEFAULT 5;

DELIMITER //

CREATE TRIGGER UPDATE_DRIVER_STAR_ON_INSERT
AFTER INSERT
ON COMPLETED_TRIP
FOR EACH ROW
BEGIN
    DECLARE driver_id INT;
    SELECT DRIVER_ID INTO driver_id FROM ASSIGNED_TRIP WHERE TRIP_ID = NEW.TRIP_ID;
    UPDATE DRIVER
    SET DRIVER_STAR = (
        SELECT COALESCE(AVG(RATING_STARS), 5.00)
        FROM COMPLETED_TRIP _CT
        JOIN ASSIGNED_TRIP _AT ON _CT.TRIP_ID = _AT.TRIP_ID
        WHERE _AT.DRIVER_ID = driver_id
    ) WHERE ACCOUNT_ID = driver_id;
END//

CREATE TRIGGER UPDATE_DRIVER_STAR_ON_UPDATE
AFTER UPDATE
ON COMPLETED_TRIP
FOR EACH ROW
BEGIN
    DECLARE driver_id INT;
    IF NEW.RATING_STARS != OLD.RATING_STARS THEN
        SELECT DRIVER_ID INTO driver_id FROM ASSIGNED_TRIP WHERE TRIP_ID = NEW.TRIP_ID;
        UPDATE DRIVER
        SET DRIVER_STAR = (
            SELECT COALESCE(AVG(RATING_STARS), 5.00)
            FROM COMPLETED_TRIP _CT
            JOIN ASSIGNED_TRIP _AT ON _CT.TRIP_ID = _AT.TRIP_ID
            WHERE _AT.DRIVER_ID = driver_id
        ) WHERE ACCOUNT_ID = driver_id;
    END IF;
END//

CREATE TRIGGER UPDATE_DRIVER_STAR_ON_DELETE
AFTER DELETE
ON COMPLETED_TRIP
FOR EACH ROW
BEGIN
    DECLARE driver_id INT;
    SELECT DRIVER_ID INTO driver_id FROM ASSIGNED_TRIP WHERE TRIP_ID = OLD.TRIP_ID;
    UPDATE DRIVER
    SET DRIVER_STAR = (
        SELECT COALESCE(AVG(RATING_STARS), 5.00)
        FROM COMPLETED_TRIP _CT
        JOIN ASSIGNED_TRIP _AT ON _CT.TRIP_ID = _AT.TRIP_ID
        WHERE _AT.DRIVER_ID = driver_id
    ) WHERE ACCOUNT_ID = driver_id;
END//

DELIMITER ;